services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: culinary
      POSTGRES_PASSWORD: culinary
      POSTGRES_DB: culinary
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U culinary"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep -q PONG" ]
      interval: 10s
      timeout: 5s
      retries: 3

  culinary-heaven:
    build:
      context: ./culinary_heaven
    container_name: culinary_heaven
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    container_name: culinary_heaven_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - culinary-heaven

volumes:
  static_volume:
  media_volume:

